# Generated by Django 6.0.8 on 2026-09-11 00:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom affiché')),
                ('kind', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('fondation', 'Fondation'), ('collectivite', 'Collectivité'), ('association', 'Association')], default='particulier', max_length=20, verbose_name='type')),
                ('public', models.BooleanField(default=False, help_text='Uniquement avec le consentement explicite du donateur (RGPD).', verbose_name='apparaît publiquement')),
                ('since', models.DateField(default=django.utils.timezone.localdate, verbose_name='soutien depuis')),
            ],
            options={
                'verbose_name': 'donateur',
                'ordering': ['-since', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuideBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre')),
                ('url', models.URLField(verbose_name='adresse')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='en une phrase')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'livre du guide',
                'verbose_name_plural': 'livres du guide',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=200, verbose_name='en une phrase')),
                ('description', models.TextField(blank=True)),
                ('retention', models.TextField(blank=True, help_text="Ce qui reste anonyme, et ce que l'association doit conserver en tant qu'hébergeur.", verbose_name="ce que l'association conserve")),
                ('url', models.URLField(blank=True, verbose_name='adresse du service')),
                ('featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('active', models.BooleanField(default=True, verbose_name='proposé')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'service',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_digest', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voisinternet_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compte',
            },
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'verbose_name': 'raccourci',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='services',
            field=models.ManyToManyField(related_name='accounts', through='core.Shortcut', to='core.service'),
        ),
        migrations.AddConstraint(
            model_name='shortcut',
            constraint=models.UniqueConstraint(fields=('account', 'service'), name='unique_shortcut'),
        ),
    ]
