# Generated by Django 6.0.8 on 2026-09-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Par exemple : « Une association ».', max_length=80, verbose_name='vous êtes…')),
                ('slug', models.SlugField(unique=True)),
                ('who', models.CharField(blank=True, max_length=200, verbose_name='qui est concerné')),
                ('pitch', models.CharField(max_length=240, verbose_name='en une phrase')),
                ('note', models.TextField(blank=True, verbose_name='texte de la page')),
                ('partnership', models.BooleanField(default=False, help_text='Pour les acteurs publics et sociaux : la page propose un partenariat, sans bouton « Ajouter ».', verbose_name='partenariat plutôt que services')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'public',
                'verbose_name_plural': 'publics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='audiences',
            field=models.ManyToManyField(blank=True, help_text="Laisser vide si le service s'adresse à tout le monde.", related_name='services', to='core.audience', verbose_name='publics'),
        ),
    ]
