# Generated by Django 6.0.8 on 2026-09-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcut',
            options={'ordering': ['account', 'position', 'service__name'], 'verbose_name': 'raccourci'},
        ),
        migrations.AddField(
            model_name='shortcut',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre personnel'),
        ),
    ]
