# Generated by Django 6.0.8 on 2026-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shortcut_options_shortcut_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='name_ar',
            field=models.CharField(help_text='Par exemple : « Une association ».', max_length=80, null=True, verbose_name='vous êtes…'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_en',
            field=models.CharField(help_text='Par exemple : « Une association ».', max_length=80, null=True, verbose_name='vous êtes…'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_es',
            field=models.CharField(help_text='Par exemple : « Une association ».', max_length=80, null=True, verbose_name='vous êtes…'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_fr',
            field=models.CharField(help_text='Par exemple : « Une association ».', max_length=80, null=True, verbose_name='vous êtes…'),
        ),
        migrations.AddField(
            model_name='audience',
            name='name_ko',
            field=models.CharField(help_text='Par exemple : « Une association ».', max_length=80, null=True, verbose_name='vous êtes…'),
        ),
        migrations.AddField(
            model_name='audience',
            name='note_ar',
            field=models.TextField(blank=True, null=True, verbose_name='texte de la page'),
        ),
        migrations.AddField(
            model_name='audience',
            name='note_en',
            field=models.TextField(blank=True, null=True, verbose_name='texte de la page'),
        ),
        migrations.AddField(
            model_name='audience',
            name='note_es',
            field=models.TextField(blank=True, null=True, verbose_name='texte de la page'),
        ),
        migrations.AddField(
            model_name='audience',
            name='note_fr',
            field=models.TextField(blank=True, null=True, verbose_name='texte de la page'),
        ),
        migrations.AddField(
            model_name='audience',
            name='note_ko',
            field=models.TextField(blank=True, null=True, verbose_name='texte de la page'),
        ),
        migrations.AddField(
            model_name='audience',
            name='pitch_ar',
            field=models.CharField(max_length=240, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='audience',
            name='pitch_en',
            field=models.CharField(max_length=240, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='audience',
            name='pitch_es',
            field=models.CharField(max_length=240, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='audience',
            name='pitch_fr',
            field=models.CharField(max_length=240, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='audience',
            name='pitch_ko',
            field=models.CharField(max_length=240, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='audience',
            name='who_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='qui est concerné'),
        ),
        migrations.AddField(
            model_name='audience',
            name='who_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='qui est concerné'),
        ),
        migrations.AddField(
            model_name='audience',
            name='who_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='qui est concerné'),
        ),
        migrations.AddField(
            model_name='audience',
            name='who_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='qui est concerné'),
        ),
        migrations.AddField(
            model_name='audience',
            name='who_ko',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='qui est concerné'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='summary_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='summary_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='summary_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='summary_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='summary_ko',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='title_ar',
            field=models.CharField(max_length=120, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='title_es',
            field=models.CharField(max_length=120, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='title_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='title_ko',
            field=models.CharField(max_length=120, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ko',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='service',
            name='retention_ar',
            field=models.TextField(blank=True, help_text="Ce qui reste anonyme, et ce que l'association doit conserver en tant qu'hébergeur.", null=True, verbose_name="ce que l'association conserve"),
        ),
        migrations.AddField(
            model_name='service',
            name='retention_en',
            field=models.TextField(blank=True, help_text="Ce qui reste anonyme, et ce que l'association doit conserver en tant qu'hébergeur.", null=True, verbose_name="ce que l'association conserve"),
        ),
        migrations.AddField(
            model_name='service',
            name='retention_es',
            field=models.TextField(blank=True, help_text="Ce qui reste anonyme, et ce que l'association doit conserver en tant qu'hébergeur.", null=True, verbose_name="ce que l'association conserve"),
        ),
        migrations.AddField(
            model_name='service',
            name='retention_fr',
            field=models.TextField(blank=True, help_text="Ce qui reste anonyme, et ce que l'association doit conserver en tant qu'hébergeur.", null=True, verbose_name="ce que l'association conserve"),
        ),
        migrations.AddField(
            model_name='service',
            name='retention_ko',
            field=models.TextField(blank=True, help_text="Ce qui reste anonyme, et ce que l'association doit conserver en tant qu'hébergeur.", null=True, verbose_name="ce que l'association conserve"),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_en',
            field=models.CharField(max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_es',
            field=models.CharField(max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='en une phrase'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_ko',
            field=models.CharField(max_length=200, null=True, verbose_name='en une phrase'),
        ),
    ]
