# Generated by Django 6.0.8 on 2026-09-11 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audience_name_ar_audience_name_en_audience_name_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordre personnel')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audience')),
            ],
            options={
                'verbose_name': 'appartenance',
                'ordering': ['account', 'position', 'audience__name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(related_name='accounts', through='core.Membership', to='core.audience'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('account', 'audience'), name='unique_membership'),
        ),
    ]
