# Generated by Django 6.0.8 on 2026-09-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicecategory_service_icon_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': "secteur d'activité",
                'verbose_name_plural': "secteurs d'activité",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('individuel', 'Individuel'), ('collectif', 'Collectif')], default='individuel', max_length=20, verbose_name='individuel ou collectif')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, upload_to='annuaire/photos/', verbose_name='photo ou logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='courriel')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('website', models.URLField(blank=True, verbose_name='site ou lien')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='adresse')),
                ('public', models.BooleanField(default=False, help_text='Uniquement avec le consentement explicite de la personne ou de la structure (RGPD).', verbose_name='apparaît publiquement')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.directorysector', verbose_name='secteur')),
            ],
            options={
                'verbose_name': "fiche de l'annuaire",
                'verbose_name_plural': 'annuaire',
                'ordering': ['order', 'name'],
            },
        ),
    ]
