# Generated by Django 6.0.8 on 2026-09-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_directorysector_directoryentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoryentry',
            options={'ordering': ['order', 'name'], 'verbose_name': "page de l'annuaire", 'verbose_name_plural': "pages de l'annuaire"},
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='photo',
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ville'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_intro',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="introduction de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name="texte du bouton d'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_link',
            field=models.URLField(blank=True, default='', verbose_name="lien de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='annuaire/logos/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='photo_lieu',
            field=models.ImageField(blank=True, default='', upload_to='annuaire/photos/', verbose_name='photo du lieu'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='photo_promo',
            field=models.ImageField(blank=True, default='', upload_to='annuaire/photos/', verbose_name='photo promotionnelle'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='photo_structure',
            field=models.ImageField(blank=True, default='', upload_to='annuaire/photos/', verbose_name='photo de la structure'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name="texte d'accroche"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='titre de la page'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Lien vers une vidéo (YouTube, PeerTube…) : affiché en lien, jamais intégré en cadre.', verbose_name='vidéo promotionnelle'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='courriel'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='site ou lien'),
        ),
    ]
