# Generated by Django 6.0.8 on 2026-09-11 23:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_directoryentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('start', models.DateTimeField(verbose_name='début')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='lieu')),
                ('online_url', models.URLField(blank=True, default='', help_text='Pour une participation à distance (visioconférence…).', verbose_name='lien en ligne')),
                ('public', models.BooleanField(default=True, verbose_name='publié')),
            ],
            options={
                'verbose_name': 'évènement',
                'verbose_name_plural': 'évènements',
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_entries', to='core.account', verbose_name='compte propriétaire'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='montant')),
                ('method', models.CharField(choices=[('helloasso', 'HelloAsso'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('autre', 'Autre')], default='helloasso', max_length=20, verbose_name='moyen')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='note')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.account')),
            ],
            options={
                'verbose_name': 'contribution financière',
                'verbose_name_plural': 'contributions financières',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EntrySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.directoryentry')),
            ],
            options={
                'verbose_name': 'abonnement à une fiche',
                'verbose_name_plural': 'abonnements aux fiches',
                'ordering': ['account', 'entry__name'],
                'constraints': [models.UniqueConstraint(fields=('account', 'entry'), name='unique_entry_subscription')],
            },
        ),
    ]
