# Generated by Django 6.0.8 on 2026-09-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_directoryentry_owner_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='note_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='note_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='note_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='note_fr',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='note_ko',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_intro_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="introduction de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_intro_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="introduction de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_intro_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="introduction de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_intro_fr',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="introduction de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_intro_ko',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name="introduction de l'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_label_ar',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name="texte du bouton d'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_label_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name="texte du bouton d'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_label_es',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name="texte du bouton d'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_label_fr',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name="texte du bouton d'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='cta_label_ko',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name="texte du bouton d'appel à l'action"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='description_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='description_ko',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='name_ar',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='name_es',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='name_ko',
            field=models.CharField(max_length=120, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tagline_ar',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name="texte d'accroche"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name="texte d'accroche"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tagline_es',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name="texte d'accroche"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tagline_fr',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name="texte d'accroche"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tagline_ko',
            field=models.CharField(blank=True, default='', max_length=240, null=True, verbose_name="texte d'accroche"),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='title_ar',
            field=models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='titre de la page'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='titre de la page'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='title_es',
            field=models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='titre de la page'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='title_fr',
            field=models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='titre de la page'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='title_ko',
            field=models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='titre de la page'),
        ),
        migrations.AddField(
            model_name='directorysector',
            name='name_ar',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directorysector',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directorysector',
            name='name_es',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directorysector',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='directorysector',
            name='name_ko',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_ar',
            field=models.CharField(max_length=120, null=True, verbose_name='nom affiché'),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='nom affiché'),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_es',
            field=models.CharField(max_length=120, null=True, verbose_name='nom affiché'),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, verbose_name='nom affiché'),
        ),
        migrations.AddField(
            model_name='donor',
            name='name_ko',
            field=models.CharField(max_length=120, null=True, verbose_name='nom affiché'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ko',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_es',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_fr',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ko',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ar',
            field=models.CharField(max_length=140, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=140, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_es',
            field=models.CharField(max_length=140, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=140, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ko',
            field=models.CharField(max_length=140, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_es',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ko',
            field=models.CharField(max_length=80, null=True, verbose_name='nom'),
        ),
    ]
