# Generated by Django 6.0.8 on 2026-09-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contribution_note_ar_contribution_note_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='audiences',
            field=models.ManyToManyField(blank=True, help_text="Laisser vide si la fiche s'adresse à tout le monde.", related_name='directory_entries', to='core.audience', verbose_name='publics'),
        ),
    ]
