# Generated by Django 6.0.8 on 2026-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_directoryentry_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='published',
            field=models.BooleanField(default=True, verbose_name='publié'),
        ),
    ]
