# Generated by Django 6.0.8 on 2026-09-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_guidebook_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryentry',
            name='photo_lieu',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='photo_structure',
        ),
        migrations.CreateModel(
            name='DirectoryEntryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annuaire/photos/', verbose_name='photo')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='légende')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='core.directoryentry')),
            ],
            options={
                'verbose_name': "photo de l'annuaire",
                'verbose_name_plural': "photos de l'annuaire",
                'ordering': ['order', 'pk'],
            },
        ),
    ]
