# Generated by Django 6.0.8 on 2026-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_directoryentry_photo_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
