# Generated by Django 6.0.8 on 2026-09-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_directoryentry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_uid',
            field=models.CharField(blank=True, default='', help_text="Identifiant de l'évènement dans l'agenda source, pour réimporter sans dupliquer.", max_length=64, verbose_name='identifiant source'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text="Page de l'évènement sur l'agenda source (OpenAgenda…).", verbose_name='lien source'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
