# Generated by Django 6.0.8 on 2026-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_latitude_event_longitude_event_source_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='agenda/photos/', verbose_name='photo'),
        ),
    ]
