# Generated by Django 6.0.8 on 2026-09-15 09:13

from django.db import migrations, models


def copy_public_to_visibility(apps, schema_editor):
    DirectoryEntry = apps.get_model("core", "DirectoryEntry")
    DirectoryEntry.objects.filter(public=True).update(visibility="public")
    DirectoryEntry.objects.filter(public=False).update(visibility="draft")


def copy_visibility_to_public(apps, schema_editor):
    DirectoryEntry = apps.get_model("core", "DirectoryEntry")
    DirectoryEntry.objects.filter(visibility="public").update(public=True)
    DirectoryEntry.objects.exclude(visibility="public").update(public=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='code postal'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='région'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publié'), ('protected', 'Brouillon protégé'), ('draft', 'Non publié')], default='draft', help_text="Publié : visible de tout le monde et référencé dans l'annuaire. Brouillon protégé : absent de l'annuaire, visible uniquement par les personnes ayant un compte sur le site. Non publié : visible uniquement par vous.", max_length=20, verbose_name='visibilité'),
        ),
        migrations.RunPython(copy_public_to_visibility, copy_visibility_to_public),
        migrations.RemoveField(
            model_name='directoryentry',
            name='public',
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Numéro, type et nom de voie : « 12, rue de la Paix ».', max_length=200, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='country',
            field=models.CharField(blank=True, choices=[('France', 'France'), ('Belgique', 'Belgique'), ('Suisse', 'Suisse'), ('Luxembourg', 'Luxembourg'), ('Allemagne', 'Allemagne'), ('Espagne', 'Espagne'), ('Italie', 'Italie'), ('Portugal', 'Portugal'), ('Royaume-Uni', 'Royaume-Uni'), ('Maroc', 'Maroc'), ('Algérie', 'Algérie'), ('Tunisie', 'Tunisie'), ('Sénégal', 'Sénégal'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Canada', 'Canada'), ('Autre', 'Autre')], default='France', max_length=100, verbose_name='pays'),
        ),
    ]
