# Generated by Django 6.0.8 on 2026-09-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_directoryentry_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='approved',
            field=models.BooleanField(default=False, verbose_name="validée par l'administration"),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text="Une intervention d'un administrateur est nécessaire avant que le service ne soit actif pour la personne (ex. création manuelle d'une boîte courriel) : le raccourci reste « en attente » jusqu'à validation (groupe « Administration »).", verbose_name='nécessite une validation'),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='validé'),
        ),
    ]
