# Generated by Django 6.0.8 on 2026-09-15 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_administration_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved', models.BooleanField(default=None, null=True, verbose_name='validée')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to='core.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to='core.directoryentry')),
            ],
            options={
                'verbose_name': 'demande de responsabilité de fiche',
                'verbose_name_plural': 'demandes de responsabilité de fiche',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'account'), name='unique_ownership_claim')],
            },
        ),
    ]
