# Generated by Django 6.0.8 on 2026-09-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_administration_group_ownershipclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'étiquette',
                'verbose_name_plural': 'étiquettes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='layout',
            field=models.CharField(choices=[('classique', 'Classique'), ('carte', 'Carte de visite'), ('magazine', 'Magazine'), ('minimal', 'Minimal'), ('vitrine', 'Vitrine'), ('profil', 'Profil'), ('affiche', 'Affiche')], default='classique', help_text="L'habillage visuel de votre fiche : choisissez celui qui vous ressemble le plus.", max_length=20, verbose_name='présentation'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='directory_entries', to='core.tag', verbose_name='étiquettes'),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='services', to='core.tag', verbose_name='étiquettes'),
        ),
    ]
