# Generated by Django 6.0.8 on 2026-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tag_directoryentry_layout_directoryentry_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.tag', verbose_name='étiquettes'),
        ),
    ]
