# Generated by Django 6.0.8 on 2026-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_backfill_approved_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='mis en avant'),
        ),
    ]
