# Generated by Django 6.0.8 on 2026-09-16 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Comptes autorisés à gérer cet évènement, en plus du groupe « Administration ».', related_name='managed_events', to='core.account', verbose_name='responsables'),
        ),
        migrations.CreateModel(
            name='EventManagementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved', models.BooleanField(default=None, null=True, verbose_name='validée')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_management_requests', to='core.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_requests', to='core.event')),
            ],
            options={
                'verbose_name': "demande de gestion d'évènement",
                'verbose_name_plural': "demandes de gestion d'évènement",
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('event', 'account'), name='unique_event_management_request')],
            },
        ),
    ]
