# Generated by Django 6.0.8 on 2026-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_administration_group_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_es',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_fr',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ko',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
    ]
