# Generated by Django 6.0.8 on 2026-09-17 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tag_name_ar_tag_name_en_tag_name_es_tag_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrysubscription',
            name='notify_email',
            field=models.BooleanField(default=False, verbose_name='notifications par courriel'),
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('interested', 'Intéressé·e'), ('going', "J'y vais")], default='interested', max_length=20, verbose_name='intention')),
                ('notify_email', models.BooleanField(default=False, verbose_name='notifications par courriel')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_interests', to='core.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.event')),
            ],
            options={
                'verbose_name': 'intérêt pour un évènement',
                'verbose_name_plural': 'intérêts pour un évènement',
                'ordering': ['account', 'event__start'],
                'constraints': [models.UniqueConstraint(fields=('account', 'event'), name='unique_event_interest')],
            },
        ),
    ]
