# Generated by Django 6.0.8 on 2026-09-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_entrysubscription_notify_email_eventinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='kind',
            field=models.CharField(choices=[('pledge', 'Promesse'), ('payment', 'Paiement')], default='payment', max_length=10, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='tax_deductible',
            field=models.BooleanField(default=False, help_text='Éligible à un reçu fiscal (don à une association loi 1901).', verbose_name='déduction fiscale'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='method',
            field=models.CharField(choices=[('helloasso', 'HelloAsso'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('autre', 'Autre')], default='helloasso', max_length=20, verbose_name='moyen'),
        ),
    ]
