# Generated by Django 6.0.8 on 2026-09-18 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contribution_kind_contribution_tax_deductible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, default='', max_length=140, verbose_name="nom de l'expéditeur·ice")),
                ('sender_email', models.EmailField(max_length=254, verbose_name="e-mail de l'expéditeur·ice")),
                ('message', models.TextField(verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.directoryentry', verbose_name='fiche')),
            ],
            options={
                'verbose_name': "message à une fiche de l'annuaire",
                'verbose_name_plural': "messages aux fiches de l'annuaire",
                'ordering': ['-created'],
            },
        ),
    ]
