# Generated by Django 6.0.8 on 2026-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_entrymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='approved',
            field=models.BooleanField(default=None, null=True, verbose_name="validée par l'administration"),
        ),
    ]
