# Generated by Django 6.0.8 on 2026-09-13 15:20

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_translate_homepage'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('lead', models.CharField(blank=True, default='', max_length=240, verbose_name='chapeau')),
                ('accent', models.CharField(choices=[('terracotta', 'Terracotta'), ('plum', 'Prune'), ('indigo', 'Indigo'), ('teal', 'Sarcelle'), ('moss', 'Mousse'), ('gold', 'Or')], default='teal', max_length=20, verbose_name='couleur du pôle')),
                ('ghost_tag', models.CharField(blank=True, default='', help_text='Étiquette Ghost dont les derniers articles apparaissent en bas de page.', max_length=100, verbose_name='étiquette du blog')),
                ('cards', wagtail.fields.StreamField([('card', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'texte'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})})),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='icône du pôle')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
