# Generated by Django 6.0.8 on 2026-09-13 16:02

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_seed_pole_pages'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('lead', models.CharField(blank=True, default='', max_length=240, verbose_name='chapeau')),
                ('body', wagtail.fields.StreamField([('card', 2), ('board', 6), ('documents', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'texte'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'nom'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'rôle'}), 5: ('wagtail.blocks.StructBlock', [[('name', 3), ('role', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'bureau'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'intitulé'}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'document', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 7), ('document', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'documents'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('lead', models.CharField(blank=True, default='', max_length=240, verbose_name='chapeau')),
                ('cards', wagtail.fields.StreamField([('card', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'texte'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DonationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('lead', models.CharField(blank=True, default='', max_length=240, verbose_name='chapeau')),
                ('cards', wagtail.fields.StreamField([('card', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'texte'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
