# Generated by Django 6.0.8 on 2026-09-15 22:34

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_association_manifesto_card'),
        ('core', '0022_tag_directoryentry_layout_directoryentry_tags_and_more'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='core.tag', verbose_name='étiquettes'),
        ),
        migrations.AddField(
            model_name='polepage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='poles', to='core.tag', verbose_name='étiquettes'),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('lead', models.CharField(blank=True, default='', max_length=240, verbose_name='chapeau')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='lieu')),
                ('body', wagtail.fields.StreamField([('card', 2), ('testimonial', 5), ('gallery', 9), ('documents', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'titre'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'texte'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'citation'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'auteur·rice', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('quote', 3), ('author', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'légende', 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'photos'}), 9: ('wagtail.blocks.StructBlock', [[('caption', 6), ('images', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'intitulé'}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'document', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 10), ('document', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'documents'})})),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='image de une')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='core.tag', verbose_name='étiquettes')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
