# Generated by Django 6.0.8 on 2026-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_pole_cards_to_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='mis en avant'),
        ),
    ]
