# Generated by Django 6.0.8 on 2026-09-16 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_blogpostpage_featured'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=140, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=140, null=True, verbose_name='titre')),
                ('title_es', models.CharField(max_length=140, null=True, verbose_name='titre')),
                ('title_ar', models.CharField(max_length=140, null=True, verbose_name='titre')),
                ('title_ko', models.CharField(max_length=140, null=True, verbose_name='titre')),
                ('text', models.CharField(blank=True, default='', max_length=300, verbose_name='texte')),
                ('text_fr', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='texte')),
                ('text_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='texte')),
                ('text_es', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='texte')),
                ('text_ar', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='texte')),
                ('text_ko', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='texte')),
                ('publish_start', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('publish_end', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='image')),
                ('page', models.ForeignKey(blank=True, help_text='Le bandeau pointe vers cette page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='page liée')),
            ],
            options={
                'verbose_name': "bandeau d'annonce",
                'verbose_name_plural': "bandeaux d'annonce",
            },
        ),
    ]
