# Generated by Django 6.0.8 on 2026-09-17 15:17

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_remove_blogpostpage_author_name'),
        ('core', '0031_contribution_kind_contribution_tax_deductible_and_more'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date de publication')),
                ('excerpt', models.CharField(blank=True, default='', max_length=300, verbose_name='chapeau')),
                ('body', wagtail.fields.StreamField([('prose', 0), ('callout', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery'], 'label': 'texte'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Astuce'), ('important', 'Important'), ('warning', 'Avertissement'), ('caution', 'Attention')], 'label': 'type'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'titre', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 2), ('text', 0)]], {})})),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pages', to='cms.author', verbose_name='auteur·ice')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='image de une')),
                ('tags', models.ManyToManyField(blank=True, related_name='content_pages', to='core.tag', verbose_name='étiquettes')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
