# Generated by Django 6.0.8 on 2026-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_contentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='ville'),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='pays'),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='site web'),
        ),
    ]
