# Generated by Django 6.0.8 on 2026-09-18 04:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_author_city_author_country_author_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('prose', 0), ('callout', 3), ('pull', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Astuce'), ('important', 'Important'), ('warning', 'Avertissement'), ('caution', 'Attention')], 'label': 'type'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'titre', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 2), ('text', 0)]], {}), 4: ('wagtail.blocks.StructBlock', [[('text', 0)]], {})}),
        ),
    ]
