# Generated by Django 6.0.8 on 2026-09-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_alter_contentpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Jamais affiché publiquement — sert uniquement à transmettre les messages du formulaire de contact (core.views.author_detail). Laisser vide masque le formulaire sur la page de cet·te auteur·ice.', max_length=254, verbose_name='e-mail'),
        ),
        migrations.CreateModel(
            name='AuthorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, default='', max_length=140, verbose_name="nom de l'expéditeur·ice")),
                ('sender_email', models.EmailField(max_length=254, verbose_name="e-mail de l'expéditeur·ice")),
                ('message', models.TextField(verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cms.author', verbose_name='auteur·ice')),
            ],
            options={
                'verbose_name': 'message à un·e auteur·ice',
                'verbose_name_plural': 'messages aux auteur·ices',
                'ordering': ['-created'],
            },
        ),
    ]
