# Generated by Django 6.0.8 on 2026-09-18 20:07 — retouchée à la main pour préserver le
# contenu existant : cms.StandardPage.body passe de RichTextField à StreamField
# (cms.models.ContentStreamBlock), même jeu de blocs que cms.ContentPage. Le contenu HTML
# déjà en base doit devenir un unique bloc "prose" plutôt que d'être perdu ou de rester
# du texte brut illisible pour le nouveau type de champ.
import json
import uuid

import wagtail.fields
from django.db import migrations


def convert_body_to_streamfield(apps, schema_editor):
    """
    Exécutée AVANT l'AlterField ci-dessous (dans la même migration) : à ce stade,
    apps.get_model reflète encore l'ancien champ (RichTextField, un simple TextField
    côté base) — écrire une chaîne JSON dans "body" ici revient donc à écrire
    directement les octets de la colonne, sans passer par la sérialisation StreamField
    (qui n'existe pas encore à ce point de l'historique des migrations). L'AlterField
    qui suit ne fait alors que changer la façon dont Django interprète un contenu déjà
    dans le bon format.
    """
    StandardPage = apps.get_model("cms", "StandardPage")
    for page in StandardPage.objects.all():
        html = page.body or ""
        if html.strip():
            stream_data = [{"type": "prose", "value": html, "id": str(uuid.uuid4())}]
        else:
            stream_data = []
        page.body = json.dumps(stream_data)
        page.save(update_fields=["body"])


def convert_streamfield_to_body(apps, schema_editor):
    """
    Migration inverse (manage.py migrate cms <précédente>) : reprend le HTML du
    premier bloc "prose" s'il y en a un, sinon un corps vide — perd tout bloc
    callout/pull/generic/generic_nesting ajouté depuis la conversion (limite assumée
    d'un retour en arrière vers un type de champ moins expressif).
    """
    StandardPage = apps.get_model("cms", "StandardPage")
    for page in StandardPage.objects.all():
        try:
            stream_data = json.loads(page.body or "[]")
        except (TypeError, ValueError):
            stream_data = []
        html = next((b.get("value", "") for b in stream_data if b.get("type") == "prose"), "")
        page.body = html
        page.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_contentpage_body'),
    ]

    operations = [
        migrations.RunPython(convert_body_to_streamfield, convert_streamfield_to_body),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 13)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Astuce'), ('important', 'Important'), ('warning', 'Avertissement'), ('caution', 'Attention')], 'label': 'type'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'titre', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 2), ('text', 0)]], {}), 4: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'classe', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('text', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('children', 8), ('class_name', 5)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('children', 10), ('class_name', 5)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('children', 12), ('class_name', 5)]], {})}),
        ),
    ]
