# Generated by Django 6.0.8 on 2026-09-18 20:19 — polepage/projectpage volontairement
# absents : voir le commentaire sur cms.PolePage.legacy_meta (cms/models.py) — de
# vieilles migrations de données (0006, 0017, 0019) manipulent PolePage/ProjectPage via
# le modèle courant, et une base migrée depuis zéro casserait si ce modèle déclarait un
# champ que la table n'a pas encore à ce point de l'historique.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_standardpage_body_streamfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
