# Generated by Django 6.0.8 on 2026-09-18 20:19 — polepage/projectpage retirés à la
# main : voir cms/migrations/0032_polepage_projectpage_legacy_meta_early.py, qui les
# ajoute plus tôt dans l'historique (0017/0019 en ont besoin avant ce point-ci).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_standardpage_body_streamfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='legacy_meta',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
