# Generated by Django 6.0.8 on 2026-09-18 21:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_legacy_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 13)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Astuce'), ('important', 'Important'), ('warning', 'Avertissement'), ('caution', 'Attention')], 'label': 'type'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'titre', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 2), ('text', 0)]], {}), 4: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'classe', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('text', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('children', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('children', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('children', 12)]], {})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 13)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Astuce'), ('important', 'Important'), ('warning', 'Avertissement'), ('caution', 'Attention')], 'label': 'type'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'titre', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('type', 1), ('title', 2), ('text', 0)]], {}), 4: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'classe', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h4', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'divider', 'pagebreak', 'image-gallery', 'pull'], 'label': 'texte', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('text', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('children', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('children', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('prose', 0), ('callout', 3), ('pull', 4), ('generic', 7), ('generic_nesting', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('class_name', 5), ('children', 12)]], {})}),
        ),
    ]
