# Generated by Django 6.0.8 on 2026-09-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_standardpage_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='excerpt',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='chapeau'),
        ),
    ]
